apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    CREATE DATABASE springbootdb;
    CREATE DATABASE springbootdb_test;
    CREATE DATABASE badrequestdb;
    CREATE DATABASE badrequestdb_test;