apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    CREATE DATABASE LAWN_MOWER_COMPANY_DATA;
    CREATE DATABASE LAWN_MOWER_COMPANY_DATA_TEST;
    CREATE DATABASE LAWN_MOWER_CUSTOMER_DATA;
    CREATE DATABASE LAWN_MOWER_CUSTOMER_DATA_TEST;