apiVersion: v1
kind: Service
metadata:
  name: pi-mariadb
  labels:
    app: pi-mariadb
spec:
  type: NodePort
  ports:
    - port: 3306
      nodePort: 30306
      name: pi-mariadb
  selector:
    app: pi-mariadb